version: '2.0'
services:
  frontend:
    build: ./frontend
    ports:
    - "80:80"
    network_mode: "bridge"
    #volumes:
    #- .:/code
    #- logvolume01:/var/log
    #links:
    #- redis
  backend:
    build: ./backend
    ports:
    - "8080:8080"
    network_mode: "bridge" 
    #image: redis
#volumes:
#  logvolume01: {}
